name: Flask Change Microservice Test
on: [push]
jobs:
  build:
    runs-on: amazonlinux
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.9
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
